package commit

// CommitType describes a tag used in the `[TAG] message` commit format.
// The four optional palette fields let users override the chip + message
// colors per tag from their TOML config; empty strings fall through to
// the built-in palette in `internal/tui/styles`.
type CommitType struct {
	Tag         string
	Description string
	BgBlock     string
	FgBlock     string
	BgMsg       string
	FgMsg       string
}

// Hex literals below mirror `commitTypePalette` in
// `internal/tui/styles/commit_type_palette.go`. They live here as plain
// strings so the autogenerated TOML carries a populated example palette
// for users to copy/edit, without dragging the styles package into the
// commit package's import graph. Keep both maps in sync when tweaking
// the canonical palette.

func GetDefaultCommitTypes() []CommitType {
	// Built-in CommitCraft tags. Aliased onto the canonical palette in
	// `commitTypePalette` (IMP→REFACTOR, REM→DEL, REF→REFACTOR, MOV→CHORE,
	// REL→BUILD, UI→STYLE), so the seeded hex values here mirror the alias
	// target.
	return []CommitType{
		{
			Tag:         "IMP",
			Description: "Improvements to the implementation",
			BgBlock:     "#2c4f5e", FgBlock: "#c4e0ec",
			BgMsg: "#16252e", FgMsg: "#a4c4d2",
		},
		{
			Tag:         "FIX",
			Description: "Bug fixes",
			BgBlock:     "#4a2729", FgBlock: "#f4cdcf",
			BgMsg: "#2a1416", FgMsg: "#d4a8aa",
		},
		{
			Tag:         "ADD",
			Description: "Feature additions",
			BgBlock:     "#2b3f34", FgBlock: "#d1ead9",
			BgMsg: "#182219", FgMsg: "#b9d2bf",
		},
		{
			Tag:         "REM",
			Description: "Feature removals",
			BgBlock:     "#3e1c1c", FgBlock: "#e8b6b6",
			BgMsg: "#1f0c0c", FgMsg: "#c89494",
		},
		{
			Tag:         "REF",
			Description: "Code refactoring",
			BgBlock:     "#2c4f5e", FgBlock: "#c4e0ec",
			BgMsg: "#16252e", FgMsg: "#a4c4d2",
		},
		{
			Tag:         "MOV",
			Description: "File moves or renames",
			BgBlock:     "#2a2d36", FgBlock: "#b8bcc4",
			BgMsg: "#14161c", FgMsg: "#8a8e98",
		},
		{
			Tag:         "REL",
			Description: "Release-related commits",
			BgBlock:     "#4a3422", FgBlock: "#ecc7a3",
			BgMsg: "#2a1c10", FgMsg: "#d3aa84",
		},
		{
			Tag:         "WIP",
			Description: "Work in progress",
			BgBlock:     "#4a3a25", FgBlock: "#ecd9b5",
			BgMsg: "#2a2014", FgMsg: "#d4bf95",
		},
		{
			Tag:         "DOC",
			Description: "Documentation updates",
			BgBlock:     "#2c4360", FgBlock: "#d6e4f4",
			BgMsg: "#182230", FgMsg: "#b8c5d4",
		},
		{
			Tag:         "TEST",
			Description: "Adding, updating, or fixing tests",
			BgBlock:     "#34401e", FgBlock: "#d4e3a8",
			BgMsg: "#1b2010", FgMsg: "#b1c189",
		},
		{
			Tag:         "PERF",
			Description: "Performance improvements",
			BgBlock:     "#4a2949", FgBlock: "#f1c5ee",
			BgMsg: "#271425", FgMsg: "#cfa1cb",
		},
		{
			Tag:         "SEC",
			Description: "Security improvements or vulnerability fixes",
			BgBlock:     "#4a232b", FgBlock: "#f0bdc4",
			BgMsg: "#29101a", FgMsg: "#cf99a3",
		},
		{
			Tag:         "I18N",
			Description: "Internationalization and localization (translations, locale files, message catalogs)",
			BgBlock:     "#1d4e57", FgBlock: "#c0e9f0",
			BgMsg: "#0e272c", FgMsg: "#9ccdd6",
		},
		{
			Tag:         "CHORE",
			Description: "Routine tasks, maintenance, or minor adjustments that don't affect code logic (e.g., build process, dependency updates, configuration changes)",
			BgBlock:     "#2a2d36", FgBlock: "#b8bcc4",
			BgMsg: "#14161c", FgMsg: "#8a8e98",
		},
		{
			Tag:         "CI",
			Description: "Changes to CI/CD configuration files and scripts",
			BgBlock:     "#313a55", FgBlock: "#c8d2ea",
			BgMsg: "#161a26", FgMsg: "#a3acc4",
		},
		{
			Tag:         "BUILD",
			Description: "Changes that affect the build system or external dependencies (e.g., gulp, broccli, npm)",
			BgBlock:     "#4a3422", FgBlock: "#ecc7a3",
			BgMsg: "#2a1c10", FgMsg: "#d3aa84",
		},
		{
			Tag:         "REVERT",
			Description: "Reverts a previous commit",
			BgBlock:     "#4a2f1c", FgBlock: "#ecbe9a",
			BgMsg: "#2a190d", FgMsg: "#cda07b",
		},
		{
			Tag:         "STYLE",
			Description: "Code style changes (e.g., formatting, semicolons, whitespace), without changing logic",
			BgBlock:     "#3e3268", FgBlock: "#e9e0ff",
			BgMsg: "#1d1830", FgMsg: "#c8bce0",
		},
		{
			Tag:         "UI",
			Description: "Visual changes to the interface",
			BgBlock:     "#3e3268", FgBlock: "#e9e0ff",
			BgMsg: "#1d1830", FgMsg: "#c8bce0",
		},
	}
}

// GetAddableCommitTypes lists tags that have a four-color palette in
// the styles package but are not part of the built-in default tag set,
// so they can be surfaced in the "Add tag types" popup as ready-to-add
// extras for the local `.commitcraft.toml`.
//
// Every general-purpose tag now ships as a built-in default via
// `GetDefaultCommitTypes`, so there is nothing left to add — the popup
// and `ai list-addable-tags` render their empty state. The list is kept
// (sourced from `GetDefaultLocalCommitExamplesTypes`) so re-introducing
// an opt-in extra later is a one-line change.
func GetAddableCommitTypes() []CommitType {
	return GetDefaultLocalCommitExamplesTypes()
}

// GetDefaultLocalCommitExamplesTypes returns the tags seeded as editable
// palette examples into a freshly scaffolded `.commitcraft.toml`. Every
// general-purpose tag (including `UI`) is now a built-in default, so a
// fresh local config needs no seeded examples — declare a custom tag
// here only to ship a project-specific extra.
func GetDefaultLocalCommitExamplesTypes() []CommitType {
	return []CommitType{}
}
